### ISSUE TITLE
PicklingError: Can't pickle <class 'uuid.UUID'>: it's not the same object as uuid.UUID

### ISSUE THREAD

**Issue by ashrubyfish** [noripyt/django-cachalot#112]
Hi there, I've had an intermittent issue come up using Cachalot in our production environment (Apache, mod_wsgi, Python 2.7, Django 1.12)

Every few weeks we get this error "Can't pickle <class 'uuid.UUID'>: it's not the same object as uuid.UUID", from deep inside the monkey patch layer of Cachalot.  (Example sentry stack trace below).

The only thing that fixes it is restarting Apache. It'll then go away for a day or two, sometimes a week or two, then reoccur.

`
PicklingError
Can't pickle <class 'uuid.UUID'>: it's not the same object as uuid.UUID
cachalot/monkey_patch.py in _get_result_or_execute_query at line 59
`

Researching this, I've only found 1 other person with the same issue (unresolved) at https://github.com/niwinz/django-redis/issues/319.

Reading up on the pickling error, it seems that if you import a symbol in different ways (i.e. import x x.y versus from x import y) it results in this pickling error.

I looked through all my code to ensure that UUID was being used and imported in a consistent way, checking also how the Django Postgresql code uses it (as I use models.UUIDField for primary keys). Everywhere uses it as such:

import uuid
...
uuid.UUID

Except for this place in Cachalot, utils.py

from time import time
**from uuid import UUID**

from django import VERSION as django_version
from django.db import connections
from django.db.models import QuerySet
from django.db.models.sql import Query
from django.db.models.sql.where import (
    ExtraWhere, SubqueryConstraint, WhereNode)
from django.utils.six import text_type, binary_type, PY2

from .settings import ITERABLES, cachalot_settings
from .transaction import AtomicCache

class UncachableQuery(Exception):
    pass

class IsRawQuery(Exception):
    pass

CACHABLE_PARAM_TYPES = {
    bool, int, float, Decimal, bytearray, binary_type, text_type, type(None),
    datetime.date, datetime.time, datetime.datetime, datetime.timedelta, **UUID**,
}

I suspect this is the source of the issue here. I'm going to try patching this on our project with the following changes to see if it solves the issue (may have to wait 3-4 weeks before declaring it solved given the mean-time between failures).

suggested change below:

**import uuid**
...

CACHABLE_PARAM_TYPES = {
    bool, int, float, Decimal, bytearray, binary_type, text_type, type(None),
    datetime.date, datetime.time, datetime.datetime, datetime.timedelta, **uuid.UUID**,
}

**Comment by BertrandBordage** [comment]
Django-cachalot does not pickle data directly. Pickling is done by the cache backend, so django-cachalot is not responsible of this part. By the way, the fact that you get this pickling error proves that your data is correctly handled as cachable by django-cachalot, since it’s going to the cache that triggers that error.. Also, directly importing an object or using it from the module give the same object, the only difference is that direct import is more optimised:
![image](https://user-images.githubusercontent.com/1119169/43314990-ec53c468-9194-11e8-8549-4ae988297338.png)

Closing it for now, I’ll reopen it if you provide a minimal example that involves django-cachalot.
