### ISSUE TITLE
MongoDB and Embedded Support?

### ISSUE THREAD

**Issue by lanespade** [noripyt/django-cachalot#114]
I am looking at different django caching frameworks and this is really appealing except that it doesn't support Mongo... are there any plans to support mongoengine and its Embedded types (EmbeddedDocument, EmbeddedDocumentListField, etc.)?

**Comment by BertrandBordage** [comment]
This is not possible to adapt django-cachalot for MongoDB. Django-cachalot is a simple tool that caches the Object-Relational Mapping of Django, which is built only for SQL. Django relies on that SQL standard both for creating cache keys and invalidation. Given that MongoDB is obviously not SQL, supporting MongoDB would imply to write a completely different module only for MongoDB and stuff it into django-cachalot.

Honestly, unless you’re running a 1 PB database split on 100 servers, you should consider using PostgreSQL instead of MongoDB: it’s safe, versatile, uses very little RAM & CPU and is globally faster for storing JSON.
Read @pydanny’s [article](https://www.pydanny.com/when-to-use-mongodb-with-django.html) or any of the benchmarks when searching specifically for the opposite: `mongodb is faster than postgresql`: [1](https://hackernoon.com/https-medium-com-cn007b-postgresql-vs-mongodb-6d8bdb7c1697) [2](https://www.arangodb.com/2018/02/nosql-performance-benchmark-2018-mongodb-postgresql-orientdb-neo4j-arangodb/) [3](https://www.percona.com/live/e17/sites/default/files/slides/High%20Performance%20JSON%20-%20PostgreSQL%20vs.%20MongoDB%20-%20FileId%20-%20115573.pdf) (I’m still very interested if someone comes up with reproducible tests showing the opposite :slightly_smiling_face:)
