### ISSUE TITLE
Excluding certain queries

### ISSUE THREAD

**Issue by chubz** [noripyt/django-cachalot#124]
Hi,

Is there a way to exclude certain queries from being affected by cachalot?

Case example:
While I do want queries relating to User model to be cached I would like to avoid queries regarding login or queries regarding user registration to be cached.

These happen rarely or happen often but have a no value being cached, and should hit the database, and will always hit the database so when I see that they run thorugh cache get and then cache set it seems like this should be avoided.
Any way to mark a view or decorate a view to disable cachalot on it?

**Comment by BertrandBordage** [comment]
It’s tricky to make django-cachalot disabled using a decorator or a context manager because of thread safety issues. Originally, I implemented this feature but removed it later as I discovered edge cases that couldn’t be handled properly.

That being said, you can use [`CACHALOT_UNCACHABLE_TABLES`](https://django-cachalot.readthedocs.io/en/latest/quickstart.html#cachalot-uncachable-tables) to specify that you want all queries implying `auth_user` (either as main or join table) to be uncached.

**Comment by oliwarner** [comment]
Sorry to necro but this I have a couple of report views that use **massive** queries, but the models need to be cached elsewhere.

I've noticed that there are ["uncachable" functions](https://github.com/noripyt/django-cachalot/issues/193). This might be new since this was filed. But it allows you to poison your query, and cachealot leaves the whole query alone.

But annotating `Now()` onto already-massive datasets seems wasteful. Is there really not anything we could do to more quickly and more efficiently poison a query to exclude it from cache?
