### ISSUE TITLE
CACHALOT_UNCACHABLE_TABLES in combination with django_mysql wrongly uses cached tables

### ISSUE THREAD

**Issue by gabn88** [noripyt/django-cachalot#154]
## What happened?

When using cachalot with django_mysql and the following setting:
```
CACHALOT_UNCACHABLE_TABLES = frozenset(('django_migrations', 'django_session',
                                         'Real_activities', ))
```

When I first execute:

`RealActivities.objects.filter(cached_table_1_instance__in=cached_table_1_instances).filter(cached_table_2_instance__in=cached_table_2_instances).use_index('specific_index')`

I see that the query is still cached. It possibly is because django_mysql CAN rewrite queries.
Adding or removing some of the RealActivities and then executing the same query again will show the cached result.

## What should've happened instead?
Query should not have been cached at all

## Steps to reproduce

[//]
Django 2.2
Mysql 8.0
django-mysql

**Comment by gabn88** [comment]
Update:
Maybe it is possible to use database instrumentation, like django-mysql does: https://github.com/adamchainz/django-mysql/issues/644
This makes the process more robust than monkey-patching it I think.

**Comment by Andrew-Chen-Wang** [comment]
@gabn88 It's because your table name is incorrect. You should be using the sql table name, which is your app name, underscore, table name.

**Comment by gabn88** [comment]
@Andrew-Chen-Wang Thanks for your comment, but my table name is correct. It is also working for all other views, just not for queries that involve django_mysql query rewriting.

**Comment by Andrew-Chen-Wang** [comment]
Hmm, MySQL is always an enemy of mine... I'm not very good at English, so correct me if I'm wrong: the query that you showed should NOT have been cached at all correct?

**Comment by Andrew-Chen-Wang** [comment]
@gabn88 It'd be useful if you could output some traceback. In that case, we can figure out how Django-MySQL might be interfering with cachalot. https://docs.djangoproject.com/en/dev/topics/logging/#topic-logging-parts-loggers

**Comment by Andrew-Chen-Wang** [comment]
@gabn88 Is it possible to post any traceback? It'd help me help you debug this issue.

**Comment by gabn88** [comment]
@Andrew-Chen-Wang Sorry for the late reply.
It is hard to post a traceback, as I'm not getting an error. I just get the wrong results.

I ended up disabling django-cachalot for now. Hope to re-enable it when possible.

**Comment by Andrew-Chen-Wang** [comment]
It's alright. Do you mind posting some general information from django-debug-toolbar perhaps? You can also use Django's DEBUG level logger:

```
LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
    },
    'handlers': {
        'console': {
            'level': 'NOTSET',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        }
    },
    'loggers': {
        '': {
            'handlers': ['console'],
            'level': 'NOTSET',
        },
        'django.request': {
            'handlers': ['console'],
            'propagate': False,
            'level': 'ERROR'
        }
    }
}
```

So any attribute saying "level" should be changed to DEBUG. Another inspiration where you can get loggers is from Django's documentation or [cookiecutter-django's settings/base.py](https://github.com/pydanny/cookiecutter-django).

This way there's at least some info where we could get to the bottom of this. I remember reading the linked issue from the Django-mysql library. It could have something to do with the monkey patching; that's why I'd like to know how this Django-mysql and cachalot interaction could make this impossible.

**Comment by Andrew-Chen-Wang** [comment]
@gabn88 I've added a context manager to cachalot so that you can disable cachalot.

Taking a look back at how cache keys are generated, you must be using the same query (like the exact same SQL query) which is why it's not invalidating properly; it's grabbing the cache key. Although it's somewhat strange why it's not invalidating on new creation of an object...

**Comment by Andrew-Chen-Wang** [comment]
Closing as it's stale. I'd like to hear back if v2.4.0 works!
