### ISSUE TITLE
cachalot_enabled = false isn't honored 

### ISSUE THREAD

**Issue by d3al** [noripyt/django-cachalot#171]
## What happened?
Setting cachalot_enabled = false doesn't work.

I'm using redis as my backend, caching is working.
Using the debug toolbar to confirm settings

Changing other cachalot settings are respected, such as the following works.
CACHALOT_UNCACHABLE_TABLES = frozenset(('django_migrations', 'test'))

## What should've happened instead?
cachalot_enabled = false should cause caching to be disabled as per docs

## Steps to reproduce
cachalot_enabled = false in my settings file

Restart runserver, tried debug mode

[//]: # (Include host configuration: OS, Django version, database, etc.)
cachalot = 2.3.3
django 2.2
redis.6
python 3.8
postgres 12

**Comment by Andrew-Chen-Wang** [comment]
try capatilizing CACHALOT_ENABLED

**Comment by d3al** [comment]
It's already all caps and always was on my settings file.

I've ensured there are no typo's.

Using Pycharm, I've invalidated the project cache, still not working.  
Can someone confirm this is happening with them?  I saw a previous bug 
about this in 2017 but it was closed.  I'm wondering if this has been 
happening for years?  I imagine not many people wanting to disable 
cache but I need to for local development/testing.  I prefer to do it 
this way vs not adding the app to my installed list.

Thanks

**Comment by Andrew-Chen-Wang** [comment]
Maybe try clearing the entire cache db? Or use Django DB cache instead of Redis. Tests are passing: https://github.com/noripyt/django-cachalot/blob/d0b5213014e80db2ecb78cbf0474e791414d53d8/cachalot/tests/settings.py#L30-L47

If you're using a virtualenv, go to: https://github.com/noripyt/django-cachalot/blob/d0b5213014e80db2ecb78cbf0474e791414d53d8/cachalot/monkey_patch.py#L70-L71

and set a breakpoint or print out if Line 71 is executed and the value of `LOCAL_STORAGE.cachalot_enabled`

**Comment by Andrew-Chen-Wang** [comment]
Sorry, I didn't test it yet since a little busy rn, but the last time I did use `CACHALOT_ENABLED` was on cachalot 2.3.0 and it seemed fine to me.

**Comment by d3al** [comment]
I followed your suggestions and wasn't helping.

Turns out, by removing the the cachalot.panels.CachalotPanel from my 
debugtoolbar config has resolved it.  Setting CACHALOT_ENABLED = False 
is now working.

So something in that panel is forcing it to stay on.

**Comment by Andrew-Chen-Wang** [comment]
Ah it was more of a debugging ask, but I see why anyways. When you enable the panel itself, cachalot is forcefully enabled:

https://github.com/noripyt/django-cachalot/blob/d0b5213014e80db2ecb78cbf0474e791414d53d8/cachalot/panels.py#L22-L37

I think this should be closed. What you should do with django-debug-toolbar is add the cachalot panel if the settings CACHALOT_ENABLED is false rather than always having the cachalot panel being enabled.

**Comment by Eboreg** [comment]
It's a very weird behaviour from the debug toolbar panel though. I would suggest for it to not do that.
