### ISSUE TITLE
Go back to Gitter instead of Discord

### ISSUE THREAD

**Issue by Natureshadow** [noripyt/django-cachalot#178]
I would like to request moving back to Gitter instead of Discord.

Discord is a closed platform, has unacceptable privacy terms, and is legally inaccessible by anyone younger than 16 years (so, it is discriminating against users and contributors).

Gitter is now a fully open platform (moving to the decentral Matrix system).

Please make free software accessible to everyone independent of biological attributes and without requiring everyone to accept more inhumane terms of use than necessary!

**Comment by Andrew-Chen-Wang** [comment]
I'm going to preface this comment with a Heart of Capitalism from someone who was once poor and genuinely understands diligence. So excuse my tone:

It's almost like you didn't read [Gitter's Terms of Service](https://element.io/terms-of-service):

> The Customer must ensure that all Authorised Users are at least 16 (sixteen) years old to use both our Hosting and Communication Services or such greater age required in their country to register for or use our Hosting and Communication Services.

Or Matrix system's privacy policy because in [section 2.6](https://matrix.org/legal/privacy-notice#26-our-commitment-to-childrens-privacy) those under 16 also cannot access Gitter:

> We never knowingly collect or maintain information in the Service from those we know are under 16, and no part of the Service is structured to attract anyone under 16. If you are under 16, please do not use the Service.

Why are you acting like you don't know that many kids have YouTube channels at 8. Don't you remember the scandal where pedophiles would comment on little girls' videos in 2018? Yea welcome to the Internet. Or that people use YouTube because lots of the world's videos live on YouTube. Think about how TED ED videos are designed for small children? They're great! I still watch them and even remember Hilbert's Hotel from TED and VSauce's videos from **a decade ago**. [YouTube for kids and their algorithms](https://www.youtube.com/watch?v=I7wfDenj6CQ&list=PLmg2Bj80XLYklgyufOiGfnQcqF4WzEO1v&ab_channel=TED-Ed) are horrifying but the truth is no one wants to purchase $36 a month of cable. Did you know that lots of kids use Discord to play video games because it's the best platforms to communicate through voice chats? Did you know lots of kids go to the Python Discord Server of nearly **175,000 members** to ask questions in the dedicated help channels because Reddit and GitHub and everywhere else is just not sufficient nor convenient enough? Wow, it's almost like those platforms work. Why do people use Facebook? Why is there Facebook games? Think now about Discord. They've got cash so now they can host more servers to allow voice/video calling! More gamers keep flocking there. What's the problem?

----
### Alright open source nut

For me, open source is great when it comes to tools that builders and creators need. That's why engineers and tinkerers are horrified by Apple's star shaped nuts.  But when it comes to products, there's only so much transparency. If I'm in a startup with horrible marketing skills but I can't hire anyone since I'm broke nor do I work well with teams or want to split my shares of the company, what am I going to do? I'm going to close source it so I have enough buffer time to make a good product succeed before someone else steals it and does it better than me. Then I could apply something like MariaDB's business license.

There's only so much that open source really does besides transparency. Take a look at uWebsockets; it's open source with a single contributor. Elasticsearch and PostgreSQL may be open source, but they've got enterprise products that implement more features. How did we know that toilet paper would be gone from grocery stores from the beginning of the pandemic? Because a hispanic YouTuber went to Venezuela and couldn't find a roll. Guess what? YouTube's closed source with minimum 13 year old policy but kids are there and also that's what allowed the US to prepare for mass production of more home rather than industrial toilet rolls quickly.

Poor thing that in the Gitter Terms of Service: "We are not responsible for providing internet connectivity to the Authorised Users for the use of the Services." That really sucks that SpaceX doesn't sell their satellite dishes for free and that they're engineering Starlink **closed source**. Boohoo. No, of course, they need to do it closed source otherwise they don't have revenue to pay their engineers, invest in new endeavors, and fix stuff up. Is that racist? Gitter should really find a way to expand broadband connection; maybe politics? Too bad there's millions of things government tries to do without becoming a dictatorship because they have no idea where resources should be properly allocated to; thus lobbying, especially in Germany where the Berlin airport is finally complete with climate activists protesting at opening. No one wins completely.

To me, I find it kinda sickening that your true motives is to push open source with the veil phrase of "accessible to everyone independent of biological attributes." Cut the crap; that's sounds more cliche than a deus ex machina.

---

Sorry if I offended you.

Very yours truly,
Andrew

**Comment by Natureshadow** [comment]
>It's almost like you didn't read [Gitter's Terms of Service](https://element.io/terms-of-service):
>
>> The Customer must ensure that all Authorised Users are at least 16 (sixteen) years old to use both our Hosting and Communication Services or such greater age required in their country to register for or use our Hosting and Communication Services.
>
>Or Matrix system's privacy policy because in [section 2.6](https://matrix.org/legal/privacy-notice#26-our-commitment-to-childrens-privacy) those under 16 also cannot access Gitter:
>
>> We never knowingly collect or maintain information in the Service from those we know are under 16, and no part of the Service is structured to attract anyone under 16. If you are under 16, please do not use the Service.

The issue here is not these terms of use, but that you do not understand federation. These terms of use are both irrelevant and do not need to be accepted to access a Gitter chat room.

>Why are you acting like you don't know that many kids have YouTube channels at 8. Don't you remember the scandal where pedophiles would comment on little girls' videos in 2018? Yea welcome to the Internet

I don't have the slightest idea what your point is here.

If it is "who reads ToU, if they want to take part, they can just ignore it and register anyway", Well, that is not a solution.

>To me, I find it kinda sickening that your true motives is to push open source with the veil phrase of "accessible to everyone independent of biological attributes." Cut the crap; that's sounds more cliche than a deus ex machina.

I find it interesting how you derive my "true motives" from a request to use open platforms.

My true motives are that I work ~30 hours per week in an organisation who's goal is to ensure that every user of free software can become a contributor if they want, with a focus on education. Half of its members are children excluded by the ToU of GitHub or Discord (by the way, as far as GitHub is concerned, it also currently bans users living in Iran, Syria, or North Korea — if young contributors do not matter to you, maybe adults do?).

If you find a moment to consider the real backgrounds, here are the most recent two FOSDEM talks on the topic, held by people who were banned by the ToU not too long ago (they turned 16 last year, but have been FOSS contributors for much longer):

https://fosdem.org/2021/schedule/event/schul_frei/

https://fosdem.org/2021/schedule/event/python_aleksis/

But as I understand your words, de facto freedom is not important to you, and your code is only published under an open source licence because you want downstrram users. Did I get that right?

>Sorry if I offended you.

It is hard to believe your offence was unintentional.

**Comment by Andrew-Chen-Wang** [comment]
> It is hard to believe your offence was unintentional.

Mm, the following apology is sincere: sorry about that. I think the problem was there have been too many hypocrites beside me this last year that your hypocritical statements turned a screw in me. We're all hypocrites, so, I'm sorry. 

I think you should've worded  "everyone independent of biological attributes" to be more like "everyone." Otherwise, to an American, you sound like an Instagram user taking a selfie at a protest saying "I'm helping" (as in it sounded very political). That's why I spoke of a veil. Sorry, culture differences. It's hard to remember Internet cultures does not necessarily equate to international culture (though I should've learned by now that most of GitHub is filled with Asians and Europeans...).

---
# Addressing

> do not need to be accepted to access a Gitter chat room.

Yes, just like how Google tracks you without accepting their TOS. Oh wait, the EU forced them to make a modal to force anonymous users to accept their TOS now. I can't wait for Gitter to find a cease and desist soon. Additionally, it's a "chat room." If you don't accept the TOS and register, how do you chat? No you "accept" the TOS then chat.

> I don't have the slightest idea what your point is here.... if young contributors do not matter to you, maybe adults do?

Even though I care about my kiddos, I treat them mostly the same as I treat adults. If they're here to learn, why treat them differently? As far as I'm concerned, that YouTube comment about kids becoming media stars is a comment about how useless TOS is for consumers unless they intend to do malicious actions. The TOS as you know is designed for the protection of the company. A company can't run the risk of breaking their home country's law; otherwise, there is no service to be given to anyone, regardless of age.

---

Here's my problem: we both have different political opinions of who should be able to participate. You believe everyone, regardless of background and under any political situation, should be able to participate. I find it cruel to allow some service to be used in a country if its government won't fundamentally change to allow their people to have such "de facto freedoms" (obviously by my surname there's an implicit bias). 

> My true motives are that I work ~30 hours per week in an organisation who's goal is to ensure that every user of free software can become a contributor if they want, with a focus on education.

So I appreciate that. German nonprofits must be better than American ones because American ones are just tax free businesses with high salaries. They're great to work for with low hours, no work, constant wage increases, and get out of lots of illegal marketing schemes; it's great. But retrospectively speaking, that's why I say we have different political opinions: I disagree with your *whole, but not entire* stance, but I genuinely appreciate the work. Anyhow.

Think about India or China; they tried to block GitHub and then their developers revolted -- hard. But websites like YouTube or Facebook? Still blocked, and many others along with them. If you have a friend in China and you ask them what "de facto freedom" means (in Mandarin), they give a lousy response that makes no sense to a democratized citizen. True story. And that's my political opinion of the matter. Teach them the core values first before smushing ideas or certain products or services onto them; kinda like what a missionary would do (well the positive stuff at least). Tangent, but that's what some Russian dictator/president said about some Russian engineering school not teaching ethics (I think; don't implant this in your mind since I could definitely be wrong). But build from the ground up; that's my political stance. I'll take a look at FOSDEM links, but I think you should consider the long term effect on Gitter:

---
### Gitter and open source platforms

People favor convenience and cheapness and etc. that makes them less evolutionarily viable but also societally progressive. That's why we have oligopolies. A federated internet is happening as many internet-based markets are extremely saturated. Federation is not as helpful as you think. And open source licenses because "you want downstream users" is obviously the reason people have pinned repositories, resumes, and targeted job markets in the first place and also the reason popular apps like Signal are popular. "We're open source" and yet I can't wait until the Biden administration in the land of the free passes a national security directive in January 2022 (when American Congressional campaigns ramp up) banning secure systems. When any one service becomes big, they get smacked by governments around the world. Don't mess with the government; they'll get you for tax evasion.

So you've got an internal debate. Consumers want better stuff -- services, goods, etc.. Typically those come from bigger and better companies. Amazon? Practically free delivery in a day for even some of the remote places of the United States. You don't get that with EBay or Walmart (sorry if this isn't in Germany). If you've got something like Gitter, they're small. If you keep federating the internet further, people find inconvenience and gravitate toward more dominant, centralized services like Discord. Great, Gitter lost in the eyes of investors, but maybe not for you. What if Gitter/Elemental isn't satisfied with a stagnant population? They want to grow; that's what a company does otherwise their investors are gone (there's no incentive to stay) and employees are decentivized to work with no salary increases. How will they grow? Well they have to become more like the aforementioned centralized services. And then, they become the exact same as GitHub, Discord, etc. services that ban countries like Iran, Syria, and North Korea.

If these services are not already banned by their governments, then they've been (implicitly) banned by their own governments regardless of the political cabinet. Don't mess with the government is my advice for you. You can protest, but don't test them in the long run. At least not the American, UK, and German governments... those ones know how to play... As federated as some industries may be, people only want to find the loopholes so many times.

Hope that makes sense in this rush of a writing.

**Comment by BertrandBordage** [comment]
Wow, you got a little carried away @Andrew-Chen-Wang :sweat_smile: 

About Gitter, I originally used it because it was easy to integrate with GitHub, but I always found the software buggy as hell (messages not displaying or displaying two times, broken layout issues).
I never used Discord yet, though I know it’s very trendy. I use Slack every day but I didn’t choose it because it required a hack to auto-invite people.

The discussion could be opened also on the GitHub vs Gitlab side. I hated it when I discovered that Microsoft bought GitHub after decades of open source shaming. I thought about moving to Gitlab. Gitlab was fairly limited compared to GitHub at that time and took more effort and maintenance to get working. I guess that’s why most people did the same and didn’t switch to Gitlab or even BitBucket.

So I’m personally open to either keeping Discord or switching back to Gitter. This is a small project and there are not too many discussions going on. If more than 10 people strongly want to go back to Gitter (by thumb-upping the original post for example) this is probably a good reason to switch back.

Ultimately this is @Andrew-Chen-Wang’s decision as he is the project maintainer now.

**Comment by Natureshadow** [comment]
I also must emphasize that by no means did I make any assumptions about the project as a whole based on its decision to use Discord (or GitHub, for that matter). I will not occupy that chat room as long as I need to accept ToU like Discord's to do so, but as can be seen elsewhere, that does not stop me from making contributions (some of which might be opinionated as well, but completely independent of this topic here). So, please do not make assumptions about what my request says about my FOSS contributions in general either.
