### ISSUE TITLE
Race condition?

### ISSUE THREAD

**Issue by pySilver** [noripyt/django-cachalot#191]
## What happened?

I have an app called `menus` which contains to models `Menu(models.Model)` and `MenuItem(MP_Node)`. Both tables are enabled for cache by cachalot. Note that `MenuItem` implements tree structure from `django-treebeard`.

There is an edit form that is responsible for updating particular Menu instance by creating or moving MenuItem's around.
The code responsible of that is a little bit complicated but nonetheless I'm adding it below:

```python
root = anytree.AnyNode()
            nodes = {}
            node_ids = [form.cleaned_data.get("node_id") for form in form.menu_items.ordered_forms]
            node_ids = set(instance.root_item.get_descendants().filter(id__in=node_ids).values_list("id", flat=True))

            for form in form.menu_items.ordered_forms:
                node_id = form.cleaned_data.get("node_id")
                page = form.cleaned_data.get("page")
                page_id = None
                if isinstance(page, Page):
                    page_id = page.pk

                item = {
                    "id": node_id if node_id in node_ids else None,
                    "parent_id": form.cleaned_data.get("parent_id"),
                    "data": {
                        "title": form.cleaned_data.get("title"),
                        "icon": form.cleaned_data.get("icon"),
                        "classes": form.cleaned_data.get("classes"),
                        "type": form.cleaned_data.get("type"),
                        "url": form.cleaned_data.get("url"),
                        "named_url": form.cleaned_data.get("named_url"),
                        "page_id": page_id,
                    },
                }
                if item["data"]["type"] in [
                    MenuItem.TEXT_LABEL,
                    MenuItem.CUSTOM_URL,
                    MenuItem.NAMED_URL,
                ]:
                    item["data"]["page_id"] = None

                nodes[node_id] = anytree.AnyNode(**item)
            for node in nodes.values():
                if node.parent_id == -1:
                    node.parent = root
                    continue
                node.parent = nodes[node.parent_id]

            exporter = DictExporter(
                dictcls=OrderedDict,
                attriter=lambda attrs: [(k, v) for k, v in attrs if k != "parent_id"],
            )
            bulk_data = exporter.export(root)["children"]

            # tree, iterative preorder
            stack = [(instance.root_item, node) for node in bulk_data[::-1]]
            while stack:
                parent, node_struct = stack.pop()
                parent.refresh_from_db()
                node_data = node_struct["data"].copy()
                node_data["id"] = node_struct["id"]
                if node_data["id"] is None:
                    node_obj = parent.add_child(**node_data)
                    node_ids.add(node_obj.pk)
                else:
                    node_obj = MenuItem.objects.get(pk=node_data["id"])
                    for attr, value in node_data.items():
                        if attr != "id":
                            setattr(node_obj, attr, value)
                    node_obj.save()
                    node_obj.move(parent, pos="last-child")

                if "children" in node_struct:
                    # extending the stack with the current node as the parent of
                    # the new nodes
                    stack.extend([(node_obj, node) for node in node_struct["children"][::-1]])

            # Delete outdated items
            instance.root_item.get_descendants().exclude(id__in=node_ids).delete()
```

What is happening is that while saving big menu (300+ items) and **having** live traffic at the same time I'm experiencing outdated data being stored in cache. I'm seeing changes on db level but cache data remains the same (loading edit interface shows data that does not match db level data). To confirm that theory `invalidate_cachalot menus` solves the issue.

I guess it may be a result of race condition (?) because there is lots of changes are made in a cycle:

```
while stack:
  ..
  node_obj = MenuItem.objects.get(pk=node_data["id"])
  for attr, value in node_data.items():
      if attr != "id":
          setattr(node_obj, attr, value)
  node_obj.save()
  node_obj.move(parent, pos="last-child")
```

Am I missing something? Should I simply use `api.invalidate` method in such cases?

## What should've happened instead?

Cached data should be changed.

**Comment by Andrew-Chen-Wang** [comment]
I doubt the volume of data is really the reason behind this. You should try out a couple things for me:

1. Run this against your test suite on two different versions or more and identify if there is a specific fault in a cachalot version
2. Temporarily, you may want to use the api for not using the cache: `cachalot_disabled`
3. This line got me curious `node_obj.move(parent, pos="last-child")`. The for loop you suspect to be the reason behind the error doesn't seem to be the culprit since you're simply setting an object's column/attributes with data before saving anything.

I think the `while stack` is fine so long as the data is still in the database. Why the cache isn't being updated could have to do with the latest version of cachalot. I highly recommend you opt for option 1 and inspect if downgrading resolves the issue. Thanks!

**Comment by pySilver** [comment]
@Andrew-Chen-Wang indeed this issue appeared quite recently when I upgraded cachalot from 2.3.5 to 2.4.1 
Worth adding it is not happening all the time – sometimes stale data appears to stay in cache sometimes not. But it never happened before and we are using it for a long time already. It never happen in tests or localhost, that why I suspected some kind of race condition caused by menu being rendered by the same queries on a frontend.

API invalidation obviously works. I will downgrade to 2.3.5 and test it.
I assume `cachalot_disabled` will work fine too.

**Comment by Andrew-Chen-Wang** [comment]
@pySilver I'm suspecting it's due to a new change in looking for subqueries though I'm not 100% certain: https://github.com/noripyt/django-cachalot/blob/9d528656d5a3ebc13dded407efa36a1a1f3f8880/cachalot/utils.py#L103-L118

by chance, are you ever hitting L116 or L137 of `cachalot.utils`? And what Django version are you on?

**Comment by pySilver** [comment]
@Andrew-Chen-Wang while it cannot be said for sure, downgrading to 2.3.5 helped. At least on production environment I haven't seen any evidence of the issue while doing manual (yeah, manual...) tests for ~20 times. With 2.4.1. stale results were observed around 9 out of 10 times. After downgrade none of this issue ever observed.

I'm on `Django 3.1.12`

**Comment by pySilver** [comment]
I've tried 2.4.1 (.2 is not on pypi yet?) and I've checked L116 with debugger (L137 isn't available in that version). Debugger did not stop there.

**Comment by pySilver** [comment]
My production environment is 99,99% the same as development (dockerized). However I failed to observe given faulty behavior on localhost with any of this versions. So maybe it somehow data related. I'm not an expert here.

**Comment by Andrew-Chen-Wang** [comment]
@pySilver sorry for this instability. v2.4.2 is released now (thanks for catching that!), but it won't resolve this issue. I highly doubt it's either a data error or a race condition on your side and more on my fault if 2.3.5 is working but 2.4.X is not. My guess as to what happening is either here:

1. https://github.com/noripyt/django-cachalot/blob/9d528656d5a3ebc13dded407efa36a1a1f3f8880/cachalot/utils.py#L110-L116
1. Or L129 and https://github.com/noripyt/django-cachalot/blob/9d528656d5a3ebc13dded407efa36a1a1f3f8880/cachalot/utils.py#L135-L137
1. or #192 (if you were to "merge" it)

For each option, I'd try deleting or monkey patching  those lines and using "pass" or something similar to the cachalot 2.3.5 code. For each option, monkeypatch/delete, test to see if that made a difference on production, then rollback. This would help identify which piece of code is the culprit. Unfortunately, I can't reproduce this issue, so if you don't mind, please do try testing out where the issue is occurring.

---

The only unnecessary code (such that we ignored this for Django 2.2 compatibility until the cachalot 2.4 version) is checking for those types of nodes. Viewing the utils file in comparison https://github.com/noripyt/django-cachalot/compare/v2.3.5...v2.4.2 details what type of nodes I'm checking now (they were here before Django 2.2 rolled out when I had to remove this code in the cachalot 2.3.X series).

**Comment by pySilver** [comment]
I am offline till the end of a week, but I will test this theories once I'm back.

**Comment by pySilver** [comment]
@Andrew-Chen-Wang I'm ready to monkey patch :) First thing first. Are we simply interested if specific "pass" line will be reached in my case? If so, I'll show you monkey-patched version of this lines/functions and I'll set some sentry reporting there.

**Comment by Andrew-Chen-Wang** [comment]
Yes, sorta. If you look at the diff comparison link between 2.4.2 and 2.3.5, we're mostly looking at the `utils.py` diff. Specifically, we're monkey patching/logging to see what *addition* created this mess. Thank you for taking the time to do this!

Before we continue, it may be best to do this over email to keep out private info. You can find my email in my profile.

- So, focusing only on utils.py, I'd create a sentry log on L137 (i.e. `yield lhs`) and check if that led to a stale result; if possible, replace `yield lhs` with the log code to see if stale results are still made. E.g. 

```python
if lhs is not None:
    logger.info("Hit LHS")
```

- The `elif` block on L110-116; I'd like to know which of those returns generate a stale result. For this one, immediately `return None` for the elif block and see if that returns stale results. E.g.:

```
elif h_class in (Subquery, Exists):
    logger.info("Hit subquery, exists, L137")
    return
```

Having the Queryset or knowing what it kinda looks like for each stale result (like a dummy queryset that conceals the name of your models and fields) would be useful for each log, but this is private information.

Again, send this over email please! It may look horrible, but it's for privacy sake :)

---

<details><summary>Notes for myself:</summary>

- user is using Django 3.1. LHS should only be used for Django 3.2+. There's a possibility that L137 is causing issues and I wonder if Django 3.2 would cause stale results with this new code.
- For L110-116, the subquery/exists block could be causing issues due to a loop in subqueries? It may be useful to see if adding subquery back into the block that says NothingNode would produce correct results. What may be happening is the table collection scheme is not compiling the SELECT statements correctly.
- I highly doubt that any write compilers are producing this issue since they aren't connected to most of cachalot's monkeypatching besides selecting the hash

</details>

**Comment by pySilver** [comment]
I think we can close this one. I never found the real issue behind described behaviour. It was very inconsistent and happened in production every few weeks or so. My best bet it had something to do with HA redis setup and selected expiration policy OR misconfigured cachalot (my `default` cache was ha redis but I've also had `local` thread cache and I did not explicitly specify that cachalot must use the `default` one). Long story short - I've migrated to memcached and explicitly set `default` cache setup in cachalot. No issues for few months since then.
