### ISSUE TITLE
Is there a recommended way to turn off cachalot on a production DB without any downtime? 

### ISSUE THREAD

**Issue by zehawki** [noripyt/django-cachalot#233]
## Question

Ive been using Cachalot for the last 3 odd years (Thanks Cachalot!) and now its served its purpose and I would like to turn it off. Setup - 
1. there are multiple EC2s with memcache as the backend for Cachalot connected to the DB (RDS).
2. memcache is setup in shared mode across the servers
3. cache invalidation is setup as per https://django-cachalot.readthedocs.io/en/latest/limits.html?highlight=caches#multiple-cache-servers-for-the-same-database

Is there a recommended way to turn off cachalot on a production DB without any downtime? And is there be any impact that I should be aware of?

Or is it as simple as removing from INSTALLED_APPS?

**Comment by BertrandBordage** [comment]
It depends on what you define by “without any downtime”. Removing it from `INSTALLED_APPS` dynamically will have no effect, but removing it from `INSTALLED_APPS` and restarting your servers will indeed disable it. If you have setup correctly your load balancing, you can restart your instances one by one and should not have downtime while gradually disabling django-cachalot.

An even smoother approach would be to set [`CACHALOT_ENABLED = False`](https://django-cachalot.readthedocs.io/en/latest/quickstart.html#cachalot-enabled) (not dynamically, but as a code change) then restart the instances one by one. That way, the invalidation of cache on freshly restarted instances will still happen, meaning the non-restarted instances will not display stale data.
Once all the instances are restarted, you can remove `'cachalot'` from `INSTALLED_APPS` and `django-cachalot` from requirements and restart again instances one by one.

All that assumes of course that there is a load balancer in front of all those instances, so that requests are never dispatched to down instances.

**Comment by zehawki** [comment]
Thank you @BertrandBordage  for the detailed reply. I finally took the plunge on this today.

Yes, there is a load balancer in front of course.

1. Turned off CACHELOT_ENABLED and restarted django server
2. Removed from INSTALLED_APPS and restarted django server
3. Turned off CACHES  and restarted django server
4. Turned off cache invalidation from the models and restarted django server
5. Finally turned off the memcached service
