### ISSUE TITLE
Msssql future support

### ISSUE THREAD

**Issue by dimkoug** [noripyt/django-cachalot#237]
Hello 

I use a django project with mssql as a database  with the package django-mssql 

So it is possible to a feature version to support  mssql , is there any plan about this  database backend ?

Thanks a lot !!!

**Comment by BertrandBordage** [comment]
Sorry, but there is no plan to support Microsoft SQL server. It's not open source and it would require to pay a license just to get started, for a database marginally used by Django users. Just for these reasons, it's not worth it. And technically, it would require us to learn all the little implementation details of Microsoft SQL server, otherwise invalidations will not work properly.

**Comment by dimkoug** [comment]
Ok thanks for the update
